export const Stages = {
  CONFIGURE: 'CONFIGURE',
  HEAD_POSITION: 'HEAD_POSITION',
  EXERCISES: 'EXERCISES',
  FEEDBACK: 'FEEDBACK',
  REVIEW: 'REVIEW'
};

export const Status = {
  INITIALISED: 'INITIALISED',
  IN_PROGRESS: 'IN_PROGRESS',
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETE: 'COMPLETE',
};
