export const Stages = {
  CONFIGURE: 'CONFIGURE',
  BODY_POSITION: 'BODY_POSITION',
  EXERCISES: 'EXERCISES',
  REVIEW: 'REVIEW',
  FEEDBACK: 'FEEDBACK'
};

export const Status = {
  INITIALISED: 'INITIALISED',
  IN_PROGRESS: 'IN_PROGRESS',
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETE: 'COMPLETE',
};
